import {
  IsUUID,
  IsString,
  IsBoolean,
  IsOptional,
  IsNumber,
  IsInt,
} from 'class-validator';
import { Type } from 'class-transformer';

export class ElevenLabsSettingsDto {
  @IsUUID()
  @IsOptional() // Optional for creation, auto-generated by the database
  id?: string;

  @IsUUID()
  agentId: string;

  @Type(() => Date)
  @IsOptional()
  createdAt?: Date;

  @Type(() => Date)
  @IsOptional()
  updatedAt?: Date;

  @IsBoolean()
  @IsOptional()
  respondAudioWithAudio?: boolean = false;

  @IsBoolean()
  @IsOptional()
  alwaysRespondWithAudio?: boolean = false;

  @IsNumber()
  @IsOptional()
  stability?: number = 0.75;

  @IsNumber()
  @IsOptional()
  similarityBoost?: number = 0.75;

  @IsString()
  @IsOptional()
  selectedElevenLabsVoiceId?: string;

  @IsString()
  subscriptionTier: string;

  @IsInt()
  characterCount: number;

  @IsInt()
  characterLimit: number;

  @IsString()
  userName: string;

  @IsString()
  @IsOptional()
  elevenLabsApiKey?: string;
}
